version: '2'
services:
  banzai_test:
    build: .
    image: banzai:test
    network_mode: bridge
    depends_on:
      - broker
  worker:
    build: .
    image: banzai:test
    network_mode: bridge
    command: ["celery", "worker", "--app=worker.worker.app", "--concurrency=2", "--hostname=worker@%h", "--loglevel=INFO"]
    depends_on:
      - broker
  broker:
    image: rabbitmq:3-management
    network_mode: bridge
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
