version: '2'
services:
  redis:
    image: redis:latest 
    network_mode: bridge
  worker:
    image: banzai:test
    network_mode: bridge
    entrypoint: ["dramatiq", "banzai.main:redis_broker", "-p", "2", "-v"] 
    depends_on:
      - redis 
    volumes:
      - /archive:/archive
      - /home/mturner/scratch:/scratch

