version: '2'
services:
  redis:
    image: redis:latest 
    network_mode: bridge
    ports:
        - "6379:6379"
  worker:
    image: banzai:test
    network_mode: bridge
    entrypoint: ["dramatiq", "banzai.main:redis_broker", "-p", "2", "-v"] 
    links:
      - redis 
    volumes:
      - /archive:/archive
      - /home/mturner/scratch:/scratch
    environment:
      - REDIS_HOST=redis
